trigger:
- sql-syntax-check


# Azure SQL Database deployment
# Deploy an Azure SQL Database using DACPAC or run scripts using SQLCMD
stages:
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: windows-latest
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          echo Creating File
          cd sql
          Get-Content 00_SOURCE.sql, 10_ODS.sql, 20_CORE.sql, 30_MART.sql, 99_PROCEDURES.sql | Set-Content DEPLOYMENT_SCRIPT.sql
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: $(subscription)
        serverName: mini-dwh-server.database.windows.net # Required when authenticationType == Server || AuthenticationType == AadAuthenticationPassword || AuthenticationType == AadAuthenticationIntegrated || AuthenticationType == servicePrincipal
        databaseName: mini-dwh-db # Required when authenticationType == Server || AuthenticationType == AadAuthenticationPassword || AuthenticationType == AadAuthenticationIntegrated || AuthenticationType == servicePrincipal
        sqlUsername: $(sqlUserUsername) # Required when authenticationType == Server
        sqlPassword: $(sqlUserPassword) # Required when authenticationType == Server
        deployType: 'sqlTask' # Options: dacpacTask, sqlTask, inlineSqlTask
        sqlFile: $(Build.SourcesDirectory)/sql/DEPLOYMENT_SCRIPT.sql # Required when deployType == SqlTask

