IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'SOURCE')
BEGIN
    EXEC('CREATE SCHEMA [SOURCE]')
END
 
IF OBJECT_ID('[SOURCE].[SOURCE_CAR]', 'U') IS NOT NULL
BEGIN
    DROP TABLE [SOURCE].[SOURCE_CAR]
END

CREATE TABLE [SOURCE].[SOURCE_CAR](
    [ID] INT,
    [NAME] [nvarchar](40) NULL,
    [RELEASE_YEAR] DATETIME NULL,
    [PRICE] [INT] NULL
)

IF OBJECT_ID('[SOURCE].[SOURCE_DRIVER]', 'U') IS NOT NULL
BEGIN
    DROP TABLE [SOURCE].[SOURCE_DRIVER]
END

CREATE TABLE [SOURCE].[SOURCE_DRIVER](
    [ID] INT,
    [NAME] [nvarchar](40) NULL,
    [CAR_ID] INT NULL,
    [AGE] [INT] NULL
)