IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'MART')
BEGIN
    EXEC('CREATE SCHEMA [MART]')
END

IF OBJECT_ID('[MART].[MART_CAR_DRIVER]', 'U') IS NOT NULL
BEGIN
    DROP TABLE [MART].[MART_CAR_DRIVER]
END

CREATE TABLE [MART].[MART_CAR_DRIVER](
            [NAME_DRIVER] [nvarchar](40) NULL,
            [NAME_CAR] [nvarchar](40) NULL
)
GO

CREATE OR ALTER PROCEDURE [MART].[MART_CAR_Loader]
AS
BEGIN
            INSERT INTO [MART].[MART_CAR_DRIVER]
            SELECT
            [DRIVER].[NAME],
            [CAR].[NAME]
            FROM [CORE].[CORE_DRIVER] [DRIVER]
            LEFT JOIN [CORE].[CORE_CAR] [CAR]
            ON CAR.ID = DRIVER.CAR_ID
END

