CREATE SCHEMA [SOURCE]
GO

IF OBJECT_ID('[SOURCE].[SOURCE_CAR]', 'U') IS NULL
BEGIN
CREATE TABLE [SOURCE].[SOURCE_CAR](
            [NAME] [char](40) NULL,
            [RELEASE_YEAR] DATETIME NULL,
            [PRICE] [INT] NULL
)
END